import { IProduct } from "../interfaces/IProduct";

export class Product implements IProduct {
  id: string | null;
  nombre: string | null;
  precio: number | null;
  descripcion: string | null;
  imagen_url: string | null;


  constructor(id: string, nombre: string, imagen_url: string, precio: number, descripcion: string) {
    this.id = id;
    this.nombre = nombre;
    this.imagen_url = imagen_url
    this.precio = precio
    this.descripcion = descripcion
  }
}

// Generated by https://quicktype.io

export interface ProductsResponse {
  productos: Producto[];
}

export interface Producto {
  id: string;
  nombre: string;
  precio: number;
  descripcion: string;
  imagen_url: string;
}
