import { IProduct } from "../interfaces/IProduct";

export class Product implements IProduct {
    /*
    id: string | null;
    name: string | null;
    image: string | null;
    price: number | null;
    */
    id:          string| null;
    nombre:      string| null;
    precio:      number| null;
    descripcion: string| null;
    imagen_url:  string| null;

    constructor(product?: any) {
      this.id = product.id != null ? product.id : null;
      this.nombre = product.name != null ? product.name : null;
      this.imagen_url = product.image != null ? product.image : null;
      this.precio = product.price != null ? product.price : null;
      this.descripcion = product.descripcion != null ? product.descripcion : null;
    }
  }

  // Generated by https://quicktype.io

export interface ProductsResponse {
  productos: Producto[];
}

export interface Producto {
  id:          string;
  nombre:      string;
  precio:      number;
  descripcion: string;
  imagen_url:  string;
}
