// Generated by https://quicktype.io

import { IRegalito } from "../interfaces/IRegalito";

export class Regalito implements IRegalito {
    id: number | null;
    idUserEmit: number;
    idUserRecived: number;
    status: string;
    idProduct: string;

    constructor( idUserEmit: number, idUserRecived: number, status: string, idProduct: string) {
        this.id = null
        this.idUserEmit = idUserEmit
        this.idUserRecived = idUserRecived
        this.status = status
        this.idProduct = idProduct
    }

}


