// Generated by https://quicktype.io

import { IRegalito } from "../interfaces/IRegalito";
import { Product } from "./Product";

export class Regalito implements IRegalito {
    id: number | null;
    idUserEmit: number;
    idUserRecived: number;
    status: string;
    product: Product;

    constructor( idUserEmit: number, idUserRecived: number, status: string, product: Product) {
        this.id = null
        this.idUserEmit = idUserEmit
        this.idUserRecived = idUserRecived
        this.status = status
        this.product = product
    }

}


