import { User } from "./models";

export interface IProduct {
    id: string | null;
    name: string | null;
    image: string | null;
    price: number | null;
  }
  
  export interface IUser {
    id: number | null;
    userName: string | null;
    email: string | null;
    password: string | null;
  }
  
  // Generated by https://quicktype.io

/*
export interface  UserMeli{
  id:         number| null;
  nickname:   string| null;
  first_name: string| null;
  last_name:  string| null;
  address:    Address| null;
}

export interface Address {
  state:    string| null;
  city:     string| null;
  address:  string| null;
  zip_code: string| null;
}


  export interface LoginRespone {
    user: User,
    token: string
  }
  */